CREATE TABLE PRODUCT
(
    PRODUCT_ID   INTEGER    NOT NULL,
    PRODUCT_CODE VARCHAR(8) NOT NULL,
    PRICE        INTEGER    NOT NULL,
    PRIMARY KEY (PRODUCT_ID)
);

SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT
