CREATE TABLE USER_INFO
(
    USER_ID INTEGER NOT NULL,
    GENDER  TINYINT(1),
    AGE     INTEGER,
    JOINED  DATE    NOT NULL,
    PRIMARY KEY (USER_ID)
);

SELECT COUNT(*) - COUNT(AGE) AS USERS
FROM USER_INFO
