CREATE TABLE ITEM_INFO
(
    ITEM_ID   INTEGER      NOT NULL,
    ITEM_NAME VARCHAR(255) NOT NULL,
    RARITY    INTEGER      NOT NULL,
    PRICE     INTEGER      NOT NULL,
    PRIMARY KEY (ITEM_ID)
);

CREATE TABLE ITEM_TREE
(
    ITEM_ID        INTEGER NOT NULL,
    PARENT_ITEM_ID INTEGER,
    PRIMARY KEY (ITEM_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM_INFO (ITEM_ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_ITEM_ID) REFERENCES ITEM_INFO (ITEM_ID) ON DELETE SET NULL
);

SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
         LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
WHERE IT.ITEM_ID IS NULL
ORDER BY II.ITEM_ID DESC;
