CREATE TABLE CAR_RENTAL_COMPANY_RENTAL_HISTORY
(
    HISTORY_ID INTEGER NOT NULL,
    CAR_ID     INTEGER NOT NULL,
    START_DATE DATE    NOT NULL,
    END_DATE   DATE    NOT NULL,
    PRIMARY KEY (HISTORY_ID)
);

WITH MONTHLY_RENTAL AS (SELECT CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m') AS RENTAL_MONTH, COUNT(*) AS RENTAL_COUNT
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE START_DATE >= '2022-08-01'
                          AND START_DATE < '2022-11-01'
                        GROUP BY CAR_ID, RENTAL_MONTH),

     FILTERED_CARS AS (SELECT CAR_ID
                       FROM MONTHLY_RENTAL
                       GROUP BY CAR_ID
                       HAVING SUM(RENTAL_COUNT) >= 5)

SELECT MR.RENTAL_MONTH, MR.CAR_ID, MR.RENTAL_COUNT AS RECORDS
FROM MONTHLY_RENTAL MR
         JOIN FILTERED_CARS FC ON MR.CAR_ID = FC.CAR_ID
ORDER BY MR.RENTAL_MONTH ASC, MR.CAR_ID DESC;
