CREATE TABLE FOOD_PRODUCT
(
    PRODUCT_ID   VARCHAR(10) NOT NULL,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    PRODUCT_CD   VARCHAR(10),
    CATEGORY     VARCHAR(10),
    PRICE        NUMBER,
    PRIMARY KEY (PRODUCT_ID)
);

SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
HAVING MAX(PRICE) = PRICE
ORDER BY MAX_PRICE DESC;

-- 최적화된 가격이 가장 높은 식품을 찾기 위한 서브쿼리
SELECT FP.CATEGORY, FP.PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
         JOIN(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
              FROM FOOD_PRODUCT
              WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
              GROUP BY CATEGORY) AS MAX_PRICE_TABLE
             ON FP.CATEGORY = MAX_PRICE_TABLE AND FP.PRICE = MAX_PRICE_TABLE.MAX_PRICE
ORDER BY FP.PRICE DESC;
