CREATE TABLE FOOD_PRODUCT
(
    PRODUCT_ID   VARCHAR(10) NOT NULL,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    PRODUCT_CD   VARCHAR(10),
    CATEGORY     VARCHAR(10),
    PRICE        NUMBER,
    PRIMARY KEY (PRODUCT_ID)
);

SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);

SELECT *
FROM FOOD_PRODUCT
ORDER BY PRICE DESC
    FETCH FIRST 1 ROW ONLY;
