CREATE TABLE FISH_INFO
(
    ID        INTEGER NOT NULL,
    FISH_TYPE INTEGER NOT NULL,
    LENGTH    FLOAT,
    TIME      DATE    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FISH_NAME_INFO
(
    FISH_TYPE INTEGER NOT NULL,
    FISH_NAME VARCHAR NOT NULL,
    PRIMARY KEY (FISH_TYPE),
    FOREIGN KEY (FISH_TYPE) REFERENCES FISH_INFO (FISH_TYPE)
);

SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
         JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.LENGTH IS NOT NULL
  AND FI.LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FISH_TYPE = FI.FISH_TYPE AND LENGTH IS NOT NULL)
ORDER BY FI.ID ASC;
