CREATE TABLE ECOLI_DATA
(
    ID                   INTEGER NOT NULL,
    PARENT_ID            INTEGER,
    SIZE_OF_COLONY       INTEGER NOT NULL,
    DIFFERENTIATION_DATE DATE    NOT NULL,
    GENOTYPE             INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

-- 계속해서 틀리는 중이다. 다시 공부하고 풀어보자.
SELECT YEAR (DIFFERENTIATION_DATE) AS YEAR, MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA JOIN (
    SELECT YEAR (DIFFERENTIATION_DATE) AS YEAR, MAX (SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR (DIFFERENTIATION_DATE)
    ) AS MAX_SIZES
ON YEAR (DIFFERENTIATION_DATE) = MAX_SIZES.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;

