CREATE TABLE ITEM_INFO
(
    ITEM_ID   INTEGER NOT NULL,
    ITEM_NAME VARCHAR NOT NULL,
    RARITY    INTEGER NOT NULL,
    PRICE     INTEGER NOT NULL,
    PRIMARY KEY (ITEM_ID)
);

SELECT SUM(PRICE) AS TOTAL_PRICE
FROM ITEM_INFO
WHERE RARITY = 'LEGEND';
