CREATE TABLE CAR_RENTAL_COMPANY_CAR
(
    CAR_ID    INTEGER      NOT NULL,
    CAR_TYPE  VARCHAR(255) NOT NULL,
    DAILY_FEE INTEGER      NOT NULL,
    OPTIONS   VARCHAR(255) NOT NULL,
    PRIMARY KEY (CAR_ID);
);

SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%'
   OR OPTIONS LIKE '%열선시트%'
   OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
HAVING COUNT(*) > 0
ORDER BY CAR_TYPE ASC;
