CREATE TABLE AUTHOR
(
    AUTHOR_ID   INTEGER      NOT NULL COMMENT '저자 ID',
    AUTHOR_NAME VARCHAR(100) NOT NULL COMMENT '저자명',
    PRIMARY KEY (AUTHOR_ID)
);

CREATE TABLE BOOK
(
    BOOK_ID        INTEGER     NOT NULL COMMENT '도서 ID',
    CATEGORY       VARCHAR(50) NOT NULL COMMENT '카테고리',
    AUTHOR_ID      INTEGER     NOT NULL COMMENT '저자 ID',
    PRICE          INTEGER     NOT NULL COMMENT '판매가',
    PUBLISHED_DATE DATE        NOT NULL COMMENT '출판일',
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (AUTHOR_ID)
);

CREATE TABLE BOOK_SALES
(
    BOOK_ID    INTEGER NOT NULL COMMENT '도서 ID',
    SALES_DATE DATE    NOT NULL COMMENT '판매일',
    SALES      INTEGER NOT NULL COMMENT '판매량',
    PRIMARY KEY (BOOK_ID, SALES_DATE),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID)
);

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
         JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
         JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;
