CREATE TABLE FIRST_HALF
(
    SHIPMENT_ID INT         NOT NULL,
    FLAVOR      VARCHAR(50) NOT NULL,
    TOTAL_ORDER INT         NOT NULL,
    PRIMARY KEY (SHIPMENT_ID)
);

SELECT FLAVOR, TOTAL_ORDER
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;
