CREATE TABLE DEVELOPER_INFOS
(
    ID         VARCHAR NOT NULL UNIQUE,
    FIRST_NAME VARCHAR,
    LAST_NAME  VARCHAR,
    EMAIL      VARCHAR NOT NULL UNIQUE,
    SKILL_1    VARCHAR,
    SKILL_2    VARCHAR,
    SKILL_3    VARCHAR,
    PRIMARY KEY (ID)
);

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE SKILL_1 = 'Python' OR SKILL_2 = 'Python' OR SKILL_3 = 'Python'
ORDER BY ID ASC;
