CREATE TABLE FOOD_FACTORY
(
    FACTORY_ID   VARCHAR(10)  NOT NULL,
    FACTORY_NAME VARCHAR(50)  NOT NULL,
    ADDRESS      VARCHAR(100) NOT NULL,
    TLNO         VARCHAR(20),
    PRIMARY KEY (FACTORY_ID)
);

SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '강원도%'
ORDER BY FACTORY_ID ASC;
