CREATE TABLE USED_GOODS_BOARD
(
    BOARD_ID     VARCHAR(5)    NOT NULL,
    WRITER_ID    VARCHAR(50)   NOT NULL,
    TITLE        VARCHAR(100)  NOT NULL,
    CONTENTS     VARCHAR(1000) NOT NULL,
    PRICE        NUMBER        NOT NULL,
    CREATED_DATE DATE          NOT NULL,
    STATUS       VARCHAR(10)   NOT NULL,
    VIEWS        NUMBER        NOT NULL,
    PRIMARY KEY (BOARD_ID)
);

CREATE TABLE USED_GOODS_REPLY
(
    REPLY_ID     VARCHAR(10) NOT NULL,
    BOARD_ID     VARCHAR(5)  NOT NULL,
    WRITER_ID    VARCHAR(50) NOT NULL,
    CONTENTS     VARCHAR(1000) NULL,
    CREATED_DATE DATE        NOT NULL,
    PRIMARY KEY (REPLY_ID),
    FOREIGN KEY (BOARD_ID) REFERENCES USED_GOODS_BOARD (BOARD_ID)
);

SELECT UGB.TITLE,
       UGB.BOARD_ID,
       UGR.REPLY_ID,
       UGR.WRITER_ID,
       UGR.CONTENTS,
       DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS UGB
         JOIN USED_GOODS_REPLY AS UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE UGR.CREATED_DATE >= '2022-10-01'
  AND UGR.CREATED_DATE < '2022-11-01'
ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC;

