CREATE TABLE DOCTOR
(
    DR_NAME  VARCHAR(20) NOT NULL,
    DR_ID    VARCHAR(10) NOT NULL,
    LCNS_NO  VARCHAR(30) NOT NULL,
    HIRE_YMD DATE        NOT NULL,
    MCDP_CD  VARCHAR(6),
    TLNO     VARCHAR(50),
    PRIMARY KEY (DR_ID)
);

SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD IN ('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME ASC;
