CREATE TABLE ONLINE_SALE
(
    ONLINE_SALE_ID INTEGER NOT NULL,
    USER_ID        INTEGER NOT NULL,
    PRODUCT_ID     INTEGER NOT NULL,
    SALES_AMOUNT   INTEGER NOT NULL,
    SALES_DATE     DATE    NOT NULL,
    PRIMARY KEY (ONLINE_SALE_ID)
);

CREATE TABLE OFFLINE_SALE
(
    OFFLINE_SALE_ID INTEGER NOT NULL,
    PRODUCT_ID      INTEGER NOT NULL,
    SALES_AMOUNT    INTEGER NOT NULL,
    SALES_DATE      DATE    NOT NULL,
    PRIMARY KEY (OFFLINE_SALE_ID)
);

SELECT DATE_FORMAT(ONS.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
       ONS.PRODUCT_ID,
       ONS.USER_ID,
       ONS.SALES_AMOUNT
FROM ONLINE_SALE ONS
WHERE ONS.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

UNION ALL

SELECT DATE_FORMAT(OFFS.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
       OFFS.PRODUCT_ID,
       NULL                                     AS USER_ID,
       OFFS.SALES_AMOUNT
FROM OFFLINE_SALE OFFS
WHERE OFFS.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
