CREATE TABLE ANIMAL_INS
(
    ANIMAL_ID        VARCHAR  NOT NULL,
    ANIMAL_TYPE      VARCHAR  NOT NULL,
    DATETIME         DATETIME NOT NULL,
    INTAKE_CONDITION VARCHAR  NOT NULL,
    NAME             VARCHAR,
    SEX_UPON_INTAKE  VARCHAR  NOT NULL,
    PRIMARY KEY (ANIMAL_ID)
);

SELECT ANIMAL_TYPE, COUNT(*) AS counts
FROM ANIMAL_INS
WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
GROUP BY ANIMAL_TYPE
ORDER BY CASE
             WHEN ANIMAL_TYPE = 'Cat' THEN 1
             WHEN ANIMAL_TYPE = 'Dog' THEN 2
             END;
