CREATE TABLE CAR_RENTAL_COMPANY_RENTAL_HISTORY
(
    HISTORY_ID INTEGER NOT NULL,
    CAR_ID     INTEGER NOT NULL,
    START_DATE DATE    NOT NULL,
    END_DATE   DATE    NOT NULL,
    PRIMARY KEY (HISTORY_ID)
);

SELECT CAR_ID,
       CASE WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16' THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;
