CREATE TABLE FIRST_HALF
(
    SHIPMENT_ID INT NOT NULL,
    FLAVOR      VARCHAR(N) NOT NULL,
    TOTAL_ORDER INT NOT NULL,
    PRIMARY KEY (FLAVOR)
);

CREATE TABLE ICECREAM_INFO
(
    FLAVOR VARCHAR(N) NOT NULL,
    INGREDIENT_TYPE VARCHAR(N) NOT NULL,
    PRIMARY KEY (FLAVOR),
    FOREIGN KEY (FLAVOR) REFERENCES FIRST_HALF(FLAVOR)
);

SELECT FH.FLAVOR
FROM FIRST_HALF FH
         JOIN
     ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
WHERE FH.TOTAL_ORDER > 3000
  AND II.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FH.TOTAL_ORDER DESC;
