CREATE TABLE ANIMAL_INS
(
    ANIMAL_ID        VARCHAR NOT NULL,
    ANIMAL_TYPE      VARCHAR NOT NULL,
    DATETIME         DATE    NOT NULL,
    INTAKE_CONDITION VARCHAR NOT NULL,
    NAME             VARCHAR NOT NULL,
    SEX_UPON_INTAKE  VARCHAR NOT NULL,
    PRIMARY KEY (ANIMAL_ID)
);

SELECT *
FROM ANIMAL_INS
GROUP BY ANIMAL_ID
