CREATE TABLE ONLINE_SALE
(
    ONLINE_SALE_ID INTEGER NOT NULL,
    USER_ID        INTEGER NOT NULL,
    PRODUCT_ID     INTEGER NOT NULL,
    SALES_AMOUNT   INTEGER NOT NULL,
    SALES_DATE     DATE    NOT NULL,
    PRIMARY KEY (ONLINE_SALE_ID)
);

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;
