CREATE TABLE SKILLCODES
(
    NAME     VARCHAR(255)   NOT NULL,
    CATEGORY VARCHAR(255)   NOT NULL,
    CODE     INTEGER UNIQUE NOT NULL,
    PRIMARY KEY (CODE)
);

CREATE TABLE DEVELOPERS
(
    ID         VARCHAR(255) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(255),
    LAST_NAME  VARCHAR(255),
    EMAIL      VARCHAR(255) NOT NULL UNIQUE,
    SKILL_CODE INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (SKILL_CODE) REFERENCES SKILLCODES (CODE)
);

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
         JOIN SKILLCODES S ON (D.SKILL_CODE & S.CODE) = S.CODE
WHERE S.NAME IN ('Python', 'C#')
ORDER BY D.ID ASC;
