CREATE TABLE BOOK
(
    BOOK_ID        INTEGER     NOT NULL COMMENT '도서 ID',
    CATEGORY       VARCHAR(50) NOT NULL COMMENT '카테고리 (경제, 인문, 소설, 생활, 기술)',
    AUTHOR_ID      INTEGER     NOT NULL COMMENT '저자 ID',
    PRICE          INTEGER     NOT NULL COMMENT '판매가 (원)',
    PUBLISHED_DATE DATE        NOT NULL COMMENT '출판일',
    PRIMARY KEY (BOOK_ID)
);

SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021
  AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;
