CREATE TABLE FISH_INFO
(
    ID        INTEGER NOT NULL,
    FISH_TYPE INTEGER NOT NULL,
    LENGTH    FLOAT,
    TIME      DATE    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FISH_NAME_INFO
(
    FISH_TYPE INTEGER      NOT NULL,
    FISH_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (FISH_TYPE)
);

SELECT COUNT(FI.ID) AS FISH_COUNT
FROM FISH_INFO FI
         JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FNI.FISH_NAME IN ('BASS', 'SNAPPER');
