CREATE TABLE CAR_RENTAL_COMPANY_CAR
(
    CAR_ID    INTEGER      NOT NULL,
    CAR_TYPE  VARCHAR(255) NOT NULL,
    DAILY_FEE INTEGER      NOT NULL,
    OPTIONS   VARCHAR(255) NOT NULL,
    PRIMARY KEY (CAR_ID)
);

CREATE TABLE CAR_RENTAL_COMPANY_RENTAL_HISTORY
(
    HISTORY_ID INTEGER NOT NULL,
    CAR_ID     INTEGER NOT NULL,
    START_DATE DATE    NOT NULL,
    END_DATE   DATE    NOT NULL,
    PRIMARY KEY (HISTORY_ID),
    FOREIGN KEY (CAR_ID) REFERENCES CAR_RENTAL_COMPANY_CAR (CAR_ID)
);

CREATE TABLE CAR_RENTAL_COMPANY_DISCOUNT_PLAN
(
    PLAN_ID       INTEGER      NOT NULL,
    CAR_TYPE      VARCHAR(255) NOT NULL,
    DURATION_TYPE VARCHAR(255) NOT NULL,
    DISCOUNT_RATE INTEGER      NOT NULL,
    PRIMARY KEY (PLAN_ID)
);

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
         JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE END_DATE >= '2022-11-01'
                         AND START_DATE <= '2022-12-01')
  AND P.DURATION_TYPE LIKE '30%'
GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ('세단', 'SUV')
   AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
