CREATE TABLE FISH_INFO
(
    ID        INTEGER NOT NULL,
    FISH_TYPE INTEGER NOT NULL,
    LENGTH    FLOAT,
    TIME      DATE    NOT NULL,
    PRIMARY KEY (ID)
);

SELECT ROUND(AVG(CASE
                     WHEN LENGTH <= 10 THEN 10
                     ELSE LENGTH
    END), 3) AS AVERAGE_LENGTH
FROM FISH_INFO
